Objective-C Type Injection
ReverseApple/GhidraApple pull request #19
Opened 2024-08-22 14:31 UTC by AngeloD2022

Resolves #15

2024-09-04 13:00 UTC, AngeloD2022 commented
@fmagin Do we want to merge this or possibly investigate optimizations to this pass?

2024-09-04 19:28 UTC, fmagin commented
We need to still fix the issue that we don't abort/crash the entire analysis when encountering an `objc_alloc(param_N)` call, but as soon as that is fixed we can merge it

2024-09-04 20:51 UTC, AngeloD2022 commented
It seems there are instances where the alloc function call does not register any constant arguments. This seems to mainly be an issue with `_objc_alloc_init()` from my brief exploration.

2024-09-04 21:03 UTC, AngeloD2022 commented
I did some further investigation, and both alloc and init_alloc seem to have identical metadata by default (prototype, calling convention, etc). My guess is that this maybe requires some correction.

2024-09-05 07:53 UTC, fmagin requested changes

2024-09-05 07:53 UTC, fmagin commented on src/main/java/lol/fairplay/ghidraapple/analysis/objcclasses/OCTypeInjectorAnalyzer.kt
> +                Msg.error(this, "Failed to inject types: highFunction is null for ${function.name}")
This kind of failure seems pretty bad and should be reported via the analysis log instead.
If anything has been logged to it, a popup with the messages will show after the analysis is finished

2024-09-05 07:54 UTC, fmagin commented
> It seems there are instances where the alloc function call does not register any constant arguments.

This might be alleviated if we explicitly set up the prototype for it before?

2024-09-09 13:01 UTC, fmagin commented
@AngeloD2022 I squashed my rewritten implementation of the analyzer down to one commit and force pushed to this branch so we keep the associated discussion with it. I moved your other commits with the P-Code viewer to a new branch for you https://github.com/ReverseApple/GhidraApple/tree/AngeloD2022/pcodeViewer

2024-09-09 13:06 UTC, AngeloD2022 commented
Love it! Thank you! I'll review in a bit.

2024-09-10 23:34 UTC, merged