add class member resolution
ReverseApple/GhidraApple pull request #32
Opened 2024-12-06 16:50 UTC by AngeloD2022

2025-01-03 17:14 UTC, fmagin requested changes
I have a few comments and issues, but for the most part I'm not familiar enough with the previous code to judge the changes.

2025-01-03 17:14 UTC, fmagin commented on src/main/java/lol/fairplay/ghidraapple/analysis/passes/objcclasses/OCClassPropertiesAnalyzer.kt
> +        program.memory.getBlock("__objc_protolist") ?: return false
Doesn't this mean that the class properties analyzer will not run for binaries without an `__objc_protolist` section? this seems like a bug. Why did you add the check for `__objc_protolist` ?

2025-01-03 17:14 UTC, fmagin commented on src/main/java/lol/fairplay/ghidraapple/analysis/passes/objcclasses/OCClassPropertiesAnalyzer.kt
>          this.program = program
Why are you storing a reference to the program ?

2025-01-03 17:14 UTC, fmagin commented on src/main/java/lol/fairplay/ghidraapple/analysis/passes/objcclasses/OCMethodSignatureAnalyzer.kt
> +        this.program = program
Again, why are you storing a reference to the program?

2025-01-03 17:14 UTC, fmagin commented on src/main/java/lol/fairplay/ghidraapple/analysis/utilities/programUtils.kt
> +@Deprecated("Use parseObjCListSection instead.")
I think that we are still in an early phase of development where we can just remove deprecated code directly

2025-01-06 16:37 UTC, AngeloD2022 commented on src/main/java/lol/fairplay/ghidraapple/analysis/passes/objcclasses/OCClassPropertiesAnalyzer.kt
>          this.program = program
This was mostly just for convenience. I can remove it if it's not ideal.

2025-01-06 16:42 UTC, AngeloD2022 commented on src/main/java/lol/fairplay/ghidraapple/analysis/passes/objcclasses/OCClassPropertiesAnalyzer.kt
> +        program.memory.getBlock("__objc_protolist") ?: return false
So, this pass was promptly superseded by OCMethodAnalyzer, and I totally forgot to remove it. Good catch.

2025-01-17 20:12 UTC, merged